//LOCALHOST
### Get all rosters
GET http://localhost:3000/rosters HTTP/1.1

### Get all Schedules
GET http://localhost:3000/schedules HTTP/1.1

### Get roster member with certain ID
GET http://localhost:3000/rosters/634b9b65079ea8e3274be4b3 HTTP/1.1

### Get schedule with certain ID
GET http://localhost:3000/schedules/636089951d65da8da668f9d4 HTTP/1.1

###Create Roster Member
POST http://localhost:3000/rosters HTTP/1.1
content-type: application/json

{
    "firstName": "Alex",
    "lastName": "Newhook",
    "number": "18",
    "position": "Center",
    "shoots": "Left",
    "height": "5ft, 10in",
    "weight": "190 pds",
    "birthday": "01/28/1991" 
}

###Create Schedule
POST http://localhost:3000/schedules HTTP/1.1
content-type: application/json

{
    "date": "ANY",
    "opponent": "ANY",
    "location": "ANY",
}

### PUT or change roster member
PUT http://localhost:3000/rosters/63325f752e2406fe7c0e841a HTTP/1.1
content-type: application/json

{
    "firstName": "Alex",
    "lastName": "Newhook",
    "number": "18",
    "position": "Center",
    "shoots": "Left",
    "height": "5ft, 10in",
    "weight": "190 pds",
    "birthday": "01/28/2001" 
}

### PUT or change schedule
PUT http://localhost:3000/schedules/63325f752e2406fe7c0e841a HTTP/1.1
content-type: application/json

{
    "date": "ANY",
    "opponent": "ANY",
    "location": "ANY",
}

### DELETE Roster member
DELETE http://localhost:3000/rosters/634ccba29b7d106d8c1bfb26 HTTP/1.1

### DELETE Schedule
DELETE http://localhost:3000/schedules/634ccba29b7d106d8c1bfb26 HTTP/1.1



// PRODUCTION Deploy
### Get all rosters 
GET https://cse341personal.onrender.com/rosters

### Get all schedules
GET https://cse341personal.onrender.com/schedules

###Get roster member by ID
GET https://cse341personal.onrender.com/rosters/633bb9c7fca43db1500c9ed1

###Get schedule by ID
GET https://cse341personal.onrender.com/schedules/633bb9c7fca43db1500c9ed1

###Create roster member
POST https://cse341personal.onrender.com/rosters HTTP/1.1
content-type: application/json

{
    "firstName": "Alex",
    "lastName": "Newhook",
    "number": "18",
    "position": "Center",
    "shoots": "Left",
    "height": "5ft, 10in",
    "weight": "190 pds",
    "birthday": "01/28/2001"
}

###Create schedule
POST https://cse341personal.onrender.com/schedules HTTP/1.1
content-type: application/json

{
    "date": "ANY",
    "opponent": "ANY",
    "location": "ANY",
}

###Put or change roster member
PUT https://cse341personal.onrender.com/rosters/633bae56ac0b9eb7b5bffd4f HTTP/1.1
content-type: application/json

{
    "firstName": "Any",
    "lastName": "Any",
    "number": "Any",
    "position": "Any",
    "shoots": "Any",
    "height": "Any",
    "weight": "Any",
    "birthday": "Any" 
}

###Put or change schedule
PUT https://cse341personal.onrender.com/schedules/633bae56ac0b9eb7b5bffd4f HTTP/1.1
content-type: application/json

{
    "date": "ANY",
    "opponent": "ANY",
    "location": "ANY",
}

###Delete roster member
DELETE https://cse341personal.onrender.com/rosters/634ccd8ed8fed479b71fa9b2 HTTP/1.1

###Delete schedule
DELETE https://cse341personal.onrender.com/schedules/634ccd8ed8fed479b71fa9b2 HTTP/1.1

